\documentclass{article}
\usepackage{amsmath}
\usepackage{fullpage}

% Prevent floats from crossing section or subsection boundaries
\usepackage[section]{placeins}
% Credit for this voodoo goes to Heiko Oberdiek
\makeatletter
\AtBeginDocument{%
  \expandafter\renewcommand\expandafter\subsection\expandafter{%
    \expandafter\@fb@secFB\subsection
  }%
}

\makeatother

\title{phylostratr visuals}
\author{Zebulun Arendsee}
\begin{document}

% Assessing the significance of hits when determining phylostrata has not been
% considered carefully in phylostratigraphy literature.
%
% The phylostratigraphy problem reduces to the finding the most likely common
% ancestor of all homologs of a focal species gene.
%
% \begin{equation}
%   \hat{k}_{MLE} = \text{argmax} \left\{ P(S_i = 1) \prod_{j=1}^{i} P(S_j = 0) \right\}_{i=1}^K
% \end{equation}
%
% Where $P(S_i = 1)$ is the probability that a homolog is in some species
% descending from the ith stratum. $K$ is the total number of strata.
%
% The hypothesis that is actually being tested is not explicitly stated
%
% The common practice of choosing a rather arbitrary E-value cutoff (usually $10^{-3}$ or $10^{-5}$).

<<heat, eval=FALSE, echo=FALSE>>=
library(phylostratr)

if(file.exists('all.Rda')){
  load('all.Rda')
} else {
  default_classifier <- classify_assuming_iid(1e-5, method='bonferroni')
  results            <- readRDS('results.Rda')
  is_present         <- default_classifier(results)
  strata_table       <- stratify(results, classifier=default_classifier)
  revenants          <- find_revenants(results, classifier=default_classifier)
  strata_levels      <- levels(strata_table$mrca_name)
  strata             <- readRDS('strata.Rda')
  save.image('all.Rda')
}

# readr::write_tsv(dataframe_significance_comparison(results), "MBF.tsv")

## The pretty way that Eve hates
# myscheme <- ggplot2::scale_fill_distiller(
#     palette = "Spectral",
#     labels  = scales::percent
#   )
@

<<eval=FALSE, echo=FALSE>>=
sigmats <- make_significance_matrices(results)
versus_TIPS <- make_TIPS_comparison_matrix(strata, results, default_classfier)
jmpmat <- make_jump_matrix(results[is_present, c('qseqid', 'ps')], labels=strata_levels)
@

<<echo=FALSE, message=FALSE>>=
require(phylostratr)
require(ggplot2)
d <- readRDS('figdata.Rda')
@

<<fig1, fig.width=7, fig.height=6, echo=FALSE>>=
d$sigmats[[1]][[1]]@xlab = "Phylostratum (Bonferroni-adjusted p-value < 0.05)"
d$sigmats[[1]][[1]]@ylab = "Phylostratum (Holm-adjusted p-value < 0.05)"
d$sigmats[[2]][[1]]@xlab = "Phylostratum (Bonferroni-adjusted p-value < 1e-5)"
d$sigmats[[2]][[1]]@ylab = "Phylostratum (Bonferroni-adjusted p-value < 0.05)"
plot(d$sigmats[[1]][[1]])
@

{\bf Fig 3A.} Comparison of phylostratum classifications using
Bonferroni-ajusted cutoffs at thresholds of 0.05 versus $10^{-5}$.

\newpage

<<fig2, fig.width=7, fig.height=6, echo=FALSE>>=
plot(d$sigmats[[2]][[1]])
@

{\bf Fig 3B.} The Bonferroni correction used in {\bf 3A} is quite stringent. A
more powerful method for family-wise error handling is the Holm method. This
method will usually yield slightly younger classifications.

\newpage

<<fig3, fig.width=7, fig.height=6, echo=FALSE>>=
plot(d$versus_TIPS) +
  ggplot2::ylab("Classification with TIPs dataset") +
  ggplot2::xlab("Classification with phylostratr dataset")
@

{\bf Fig 3C.}

\newpage

<<fig4, fig.width=7, fig.height=6, echo=FALSE>>=
plot(d$jmpmat) +
  ggplot2::ylab("Young phylostratum with homolog") +
  ggplot2::xlab("Next phylostratum with homolog")
@

{\bf Fig 3D.}

\end{document}
