---
title: "*Arabidopsis thaliana* case study"
author: "Zebulun Arendsee"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{*Arabidopsis thaliana* case study}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Select relatives to search

```{r}
library(phylostratr)
library(taxize)

# Get stratified relatives represented in UniProt
strata <- uniprot_cousins(3702)

cfilter <- make_do_if_over(5, take_first)
strata2 <- clear_uncle(strata, 2759, 33154) %>%
    lapply(cfilter) %>%
    add_representative(scinames=c('Homo sapiens', 'Saccharomyces cerevisiae'))

strata3 <- as_named_strata(strata2)
print_strata(strata3)

# Get all bacterial and Archael classes (class is one level below phylum)
prokaryote_classes <- taxize::downstream(c('Bacteria', 'Archaea'), downto='class', db='ncbi')

# Get all uniprot reference genomes for each bacterial class
bacteria_class_reps <- lapply(
    prokaryote_classes$Bacteria$childtaxa_id,
    uniprot_downstream_ids, reference_only=TRUE, delay=TRUE
  )
names(bacteria_class_reps) <- prokaryote_classes$Bacteria$childtaxa_id


# Get all uniprot reference genomes for each bacterial class
archaea_class_reps <- lapply(
    prokaryote_classes$Archaea$childtaxa_id,
    uniprot_downstream_ids, reference_only=TRUE, delay=TRUE
  )
names(archaea_class_reps) <- prokaryote_classes$Archaea$childtaxa_id

# From each class, randomly select a single uniprot reference genome
sample_taxids <- function(x, ...){
    # This is required, because R is evil. If x is of length 1 and is numeric,
    # then `sample` treats it as the upperbound of a discrete distribution
    # between 1 and x. Otherwise it is treated as a set to be sampled from.
    sample(as.character(x), ...) %>% as.integer
}
set.seed(42)
bacteria_taxids <- bacteria_class_reps %>%
    Filter(f = function(x){ length(x) > 0}) %>%
    lapply(sample_taxids, size=1) %>% unlist
archaea_taxids <- archaea_class_reps %>%
    Filter(f = function(x){ length(x) > 0}) %>%
    lapply(as.character) %>%
    lapply(sample_taxids, size=1) %>% unlist

strata4 <- append(list(`131567`=list(`2`=bacteria_taxids, `2157`=archaea_taxids)), strata2)
strata5 <- as_named_strata(strata4)
print_strata(strata5)
```

```{r, eval=FALSE}
# Download genomes
uniprot_retrieve_genomes(unname(unlist(strata4)))

# Get a sample Arabidopsis thaliana protein FASTA file 
query  <- system.file(
    'extdata',
    'araport11',
    'at_ATxGx99xx.faa',
    package='phylostratr'
)

# BLAST against each target genome (this will take a few hours)
results <- strata_blast(query, strata4, blast_args=list(nthreads=8)) %>%
  strata_besthits %>%
  merge_besthits
```

```{r, eval=FALSE}
library(phylostratr)
library(magrittr)

shits <- system.file(
    'extdata',
    'araport11',
    'araport11_subset9.tab',
    package='phylostratr'
) %>%
  load_hittable %>%
  get_max_hit

shits %>%
    dplyr::group_by(staxid) %>%
    dplyr::summarize(n = n()) -> x
```
