PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?taxon
WHERE
{
    ?proteome_ref a up:Representative_Proteome .
	?proteome_ref up:organism ?taxon .
    ?taxon a up:Taxon .
    ?taxon rdfs:subClassOf taxon:TAXID .
}
